name: RUDRA App Service - CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rudra-app-service:${{ env.IMAGE_TAG }}

  deploy-production:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Pull the Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/rudra-app-service:latest

      - name: Delete Old Container
        run: |
          if [ "$(docker ps -aq -f name=rudra-app-service-container)" ]; then
            docker stop rudra-app-service-container || true
            docker rm rudra-app-service-container || true
          fi

      - name: Run the Container
        run: |
          docker run -d -p 8080:8080 \
            --name rudra-app-service-container \
            --restart unless-stopped \
            -e NODE_ENV=staging \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e REDIS_USERNAME=${{ secrets.REDIS_USERNAME }} \
            -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
            -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
            -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
            -e TWILIO_SERVICE_SID=${{ secrets.TWILIO_SERVICE_SID }} \
            -e TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} \
            -e TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} \
            -e TWILIO_APP_HASH=${{ secrets.TWILIO_APP_HASH }} \
            -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            -e SUPABASE_LOOKUP_BUCKET=${{ secrets.SUPABASE_LOOKUP_BUCKET }} \
            -e SUPABASE_SECRET_KEY=${{ secrets.SUPABASE_SECRET_KEY }} \
            -e GEOCODE_API_KEY=${{ secrets.GEOCODE_API_KEY }} \
            -e REVERSE_GEOCODE_API_KEY=${{ secrets.REVERSE_GEOCODE_API_KEY }} \
            -e SERVER_PORT=8080 \
            ${{ secrets.DOCKER_USERNAME }}/rudra-app-service:latest

  deploy-development:
    runs-on: [self-hosted, development]
    needs: build
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Pull the Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/rudra-app-service:dev

      - name: Delete Old Container
        run: |
          if [ "$(docker ps -aq -f name=rudra-app-service-container)" ]; then
            docker stop rudra-app-service-container || true
            docker rm rudra-app-service-container || true
          fi

      - name: Run the Container
        run: |
          docker run -d -p 8080:8080 \
            --name rudra-app-service-container \
            --restart unless-stopped \
            -e NODE_ENV=development \
            -e DB_HOST=${{ secrets.DEV_DB_HOST }} \
            -e DB_PORT=${{ secrets.DEV_DB_PORT }} \
            -e DB_NAME=${{ secrets.DEV_DB_NAME }} \
            -e DB_USER=${{ secrets.DEV_DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }} \
            -e JWT_SECRET=${{ secrets.DEV_JWT_SECRET }} \
            -e REDIS_USERNAME=${{ secrets.DEV_REDIS_USERNAME }} \
            -e REDIS_PASSWORD=${{ secrets.DEV_REDIS_PASSWORD }} \
            -e REDIS_HOST=${{ secrets.DEV_REDIS_HOST }} \
            -e REDIS_PORT=${{ secrets.DEV_REDIS_PORT }} \
            -e TWILIO_SERVICE_SID=${{ secrets.TWILIO_SERVICE_SID }} \
            -e TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} \
            -e TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} \
            -e TWILIO_APP_HASH=${{ secrets.TWILIO_APP_HASH }} \
            -e SUPABASE_URL=${{ secrets.DEV_SUPABASE_URL }} \
            -e SUPABASE_LOOKUP_BUCKET=${{ secrets.DEV_SUPABASE_LOOKUP_BUCKET }} \
            -e SUPABASE_SECRET_KEY=${{ secrets.DEV_SUPABASE_SECRET_KEY }} \
            -e GEOCODE_API_KEY=${{ secrets.DEV_GEOCODE_API_KEY }} \
            -e REVERSE_GEOCODE_API_KEY=${{ secrets.DEV_REVERSE_GEOCODE_API_KEY }} \
            -e SERVER_PORT=8080 \
            ${{ secrets.DOCKER_USERNAME }}/rudra-app-service:dev
